### ISSUE TITLE
Do I Need both provider and client?

### ISSUE THREAD

**Issue by okyere** [its-dirg/Flask-pyoidc#1]
Sorry if this is a basic concept. I'm a bit confused as to how to use this library as only a client that is trying to authenticate with a provider. In your notes under 'Usage', your bullet points suggest how to create a OIDCAuthentication object. Two of them are for provider and one for client. So I'm wondering if I need to create a provider object as well as a client object. In the example app in [app.py](https://github.com/its-dirg/Flask-pyoidc/blob/master/example/app.py), you created only one object which looks like one of the options of the provider object creation. Am I supposed to create another OIDCAuthentication for the client? If so, how do the two interact?

If I have to create the client registration, where do I get the redirect_uris you mention in the description?

As it stands right now, my in house provider has given me a client_id, client_secret, token and auth endpoints. How do I use these parameters and get my simple 'hello world' app authenticate with provider? Sorry for my limited understanding.

**Comment by rebeckag** [comment]
You only create one OIDCAuthentication object, the three bullets in the 'Usage' section are three different examples.

If you have gotten a client_id, client_secret and auth+token endpoints from your in-house provider it means that it does static client registration and does not support dynamic discovery. So you should create the OIDCAuthentication object as

    OIDCAuthentication(provider_configuration_info=dict(authorization_endpoint=<auth endpoint>, token_endpoint=<token endpoint>), client_registration_info=dict(client_id=<client_id>, client_secret=<client_secret>)

where you fill in the info you have received (marked with angle brackets above).

Then you have to give the redirect URI "`<flask_url>/redirect_uri`" (where `<flask_url>` is the URL for the Flask application) to your in-house provider (i.e. the person managing new client registrations).

Does this clarify it for you?

**Comment by okyere** [comment]
It is clearer now. I have a question about the redirect uri though. Do I have to create a route in with an associated view function as:

`@app.route('/redirect_me', methods=['GET', 'POST'])
def redirect_me():
    pass
`

And then give the url 'my_app.com/redirect_me' to my provider to save it as

**Comment by okyere** [comment]
Yes, it makes better sense to me now. I'll give it a shot and report back.

**Comment by okyere** [comment]
Rebecka,

I got a small problem. I'm getting:

`ImportError: No module named 'flask_pyoidc'`

I have installed flask_pyoidc with pip. I have verified that the module is in the virtual environment with 'pip list'. Yet, when I try to import the module, I get an error.

![image](https://cloud.githubusercontent.com/assets/7908765/13789566/a6e42822-eab2-11e5-813c-51c13d0cd74c.png)

Why would this be?

**Comment by rebeckag** [comment]
Sorry about that, the release on PyPI was broken!
I've released a new version, so you can do `pip install -U flask-pyoidc==0.1.1`.
After it's updated you should be able to do `import flask_pyoidc.flask_pyoidc` or even `from flask_pyoidc.flask_pyoidc import OIDCAuthentication`.

**Comment by okyere** [comment]
Great. That solved that issue. However, there's a new one. I passed in the values in the square brackets as you suggested earlier today. When I try to run, I get:

`Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from app import theapp
  File "D:\Local_Git_Repositories\Web_Applications\fbbi_dev\app\__init__.py", li
ne 9, in <module>
    client_registration_info=dict(client_id='fbbidev_ac_client', client_secret='
wP90s6eWSr4xDOSmcXHEynukXgb4F8qf6Uik9u6TdK9L4rHfcZS6nftb2QOhULit'))
  File "C:\Anaconda3\envs\fbbidev\lib\site-packages\flask_pyoidc\flask_pyoidc.py
", line 27, in __init__
    provider_configuration_info['issuer'])
KeyError: 'issuer'`

I think your logic is looking for the 'issuer' which I don't provide.

**Comment by rebeckag** [comment]
Correct, you'll have to provide the issuer URL in the provider information too:

    OIDCAuthentication(provider_configuration_info=dict(issuer=<issuer>, authorization_endpoint=<auth endpoint>, token_endpoint=<token endpoint>), client_registration_info=dict(client_id=<client_id>, client_secret=<client_secret>).

**Comment by okyere** [comment]
Thanks again. 

1. One of the links my in house provider gave me is https://some_base_url/.well-known/openid-configuration. Its output is similar to Google's https://accounts.google.com/.well-known/openid-configuration . Is that the issuer url or provider url? Is that the value I set to `issuer` ? Can` I use that url for something to make the creation of OIDCAuthentication easier?
2. Finally, I gave the provider what the redirect uri should be. eg. https:myapp.cs.com/redirectme . Do I need to create a route in flask as  `theapp.route('/redirectme')` and do something with it? I ask because I read that I'm supposed to do something with that endpoint. Sorry to bug with too many questions. My provider doesn't know much and I'm trying to learn this on my own.

**Comment by rebeckag** [comment]
1. The URL you gave contains the issuer URL, so you can simply do `OIDCAuthentication(issuer=https://some_base_url, ...)`. Don't include the path /.well-known/openid-configuration).
2. The redirect uri is handled internally by flask_pyoidc, which is why it MUST have the exact path /redirect_uri. You need to give the provider the URL `https://myapp.cs.com/redirect_uri` (replace `/redirectme` with `/redirect_uri`).

**Comment by okyere** [comment]
Thanks. After the changes, I can't start the app. This is the stacktrace : 

`[fbbidev] D:\Local_Git_Repositories\Web_Applications\fbbi_dev>
[fbbidev] D:\Local_Git_Repositories\Web_Applications\fbbi_dev>python run.py
http_request failed: HTTPSConnectionPool(host='fedloginqa.cat.com', port=443): M
ax retries exceeded with url: /.well-known/openid-configuration (Caused by Proxy
Error('Cannot connect to proxy.', ConnectionResetError(10054, 'An existing conne
ction was forcibly closed by the remote host', None, 10054, None))), url: https:
//fedloginqa.cat.com/.well-known/openid-configuration, htargs: {'allow_redirects
': False, 'verify': False}, method: GET
Traceback (most recent call last):
  File "C:\Anaconda3\envs\fbbidev\lib\site-packages\requests\packages\urllib3\co
nnectionpool.py", line 554, in urlopen
    self._prepare_proxy(conn)
  File "C:\Anaconda3\envs\fbbidev\lib\site-packages\requests\packages\urllib3\co
nnectionpool.py", line 750, in _prepare_proxy
    conn.connect()
  File "C:\Anaconda3\envs\fbbidev\lib\site-packages\requests\packages\urllib3\co
nnection.py", line 252, in connect
    ssl_version=resolved_ssl_version)
  File "C:\Anaconda3\envs\fbbidev\lib\site-packages\requests\packages\urllib3\ut
il\ssl_.py", line 305, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Anaconda3\envs\fbbidev\lib\ssl.py", line 365, in wrap_socket
    _context=self)
  File "C:\Anaconda3\envs\fbbidev\lib\ssl.py", line 583, in __init__
    self.do_handshake()
  File "C:\Anaconda3\envs\fbbidev\lib\ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] An existing connection was forcibly close
d by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\envs\fbbidev\lib\site-packages\requests\adapters.py", line
376, in send
    timeout=timeout
  File "C:\Anaconda3\envs\fbbidev\lib\site-packages\requests\packages\urllib3\co
nnectionpool.py", line 609, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Anaconda3\envs\fbbidev\lib\site-packages\requests\packages\urllib3\ut
il\retry.py", line 273, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='fe
dloginqa.cat.com', port=443): Max retries exceeded with url: /.well-known/openid
-configuration (Caused by ProxyError('Cannot connect to proxy.', ConnectionReset
Error(10054, 'An existing connection was forcibly closed by the remote host', No
ne, 10054, None)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from app import theapp
  File "D:\Local_Git_Repositories\Web_Applications\fbbi_dev\app\__init__.py", li
ne 9, in <module>
    client_secret_expires_at = 1577858400))
  File "C:\Anaconda3\envs\fbbidev\lib\site-packages\flask_pyoidc\flask_pyoidc.py
", line 23, in __init__
    self.client.provider_config(issuer)
  File "C:\Anaconda3\envs\fbbidev\lib\site-packages\oic\oic\__init__.py", line 9
15, in provider_config
    r = self.http_request(url)
  File "C:\Anaconda3\envs\fbbidev\lib\site-packages\oic\oauth2\base.py", line 56
, in http_request
    r = requests.request(method, url, **_kwargs)
  File "C:\Anaconda3\envs\fbbidev\lib\site-packages\requests\api.py", line 53, i
n request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Anaconda3\envs\fbbidev\lib\site-packages\requests\sessions.py", line
468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Anaconda3\envs\fbbidev\lib\site-packages\requests\sessions.py", line
576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Anaconda3\envs\fbbidev\lib\site-packages\requests\adapters.py", line
437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='fedloginqa.cat.co
m', port=443): Max retries exceeded with url: /.well-known/openid-configuration
(Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, 'A
n existing connection was forcibly closed by the remote host', None, 10054, None
)))`

I created a private repo on bitbucket with my entire source code. If you can help me troubleshoot, I'll appreciate it. Thanks.

**Comment by rebeckag** [comment]
Thanks, I got access to your private repo. Let's continue this discussion there. :)
